# Generated by Django 2.1.5 on 2019-01-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('idResultado', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(max_length=280)),
            ],
        ),
    ]
