# Generated by Django 2.0 on 2019-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('link', models.TextField(max_length=200)),
                ('autor', models.TextField(max_length=100)),
                ('comentarios', models.BigIntegerField(default=0)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
